service: mate-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10
  region: ap-northeast-2
  architecture: arm64
  httpApi:
    cors: true

functions:
  api:
    handler: main.handler
    events:
      - httpApi: "*"

package:
  individually: true
  patterns:
    - "!venv/**"
    - "!node_modules/**"
    - "!.git/**"
    - "!.serverless/**"
    - "!__pycache__/**"
    - "!tests/**"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    # dockerImage: public.ecr.aws/sam/build-python3.10:latest-x86_64
    slim: true
