service: mate-backend
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-2
  architecture: arm64
  httpApi:
    cors: true

  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  api:
    handler: main.handler
    events:
      - httpApi: "*"

package:
  individually: true
  patterns:
    - "lib/**"
    - "!.git/**"
    - "!.serverless/**"
    - "!venv/**"
    - "!node_modules/**"
    - "!__pycache__/**"
# plugins:
#   - serverless-python-requirements

custom:
  pythonRequirements:
      pythonBin: python
#     dockerizePip: true
#     dockerImage: public.ecr.aws/sam/build-python3.10:latest-arm64
#     layer: false
#     zip: false
#     slim: false
#     strip: false

# custom:
#   pythonRequirements:
#     dockerizePip: false
#     layer: false
#     slim: false
#     strip: false
#     zip: true
