service: mate-backend
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-2
  httpApi:
    cors: true

  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  api:
    handler: main.handler
    events:
      - httpApi: "*"
      - schedule: rate(5 minutes)

package:
  individually: true
  patterns:
    - "lib/**"
    - "!.git/**"
    - "!.serverless/**"
    - "!venv/**"
    - "!node_modules/**"
    - "!__pycache__/**"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python 
    dockerizePip: false
    strip: false
    zip: false